---
# 2. Expand upon the above template by adding a Jinja2 if conditional.  The if conditional
# should add the below SNMPv3 commands and associated ACL (i.e. if SNMPv3, then the below
# commands are added into the configuration file):

- name: Generate configuration file
  hosts: localhost
  roles:
    - router
