---
# 1. Create an Ansible playbook that generates five switch configurations based upon
# the below partial switch configuration. The hostname, ip_addr, and default_gateway
# should be unique for each switch.

- hosts: localhost
  tasks:
    - name: Generate configuration file
      template: src=/Volumes/home/mrreyes512/pyNet/git/class5/template1.j2
                dest=/Volumes/home/mrreyes512/pyNet/git/class5/CONFIGS/{{item.hostname}}.txt
      with_items:
        - {hostname: pynet-rtr1, ip_addr: 1.1.1.1, gateway: 1.1.1.255 }
        - {hostname: pynet-rtr2, ip_addr: 1.1.1.2, gateway: 1.1.1.255 }
        - {hostname: pynet-rtr3, ip_addr: 1.1.1.3, gateway: 1.1.1.255 }
        - {hostname: pynet-rtr4, ip_addr: 1.1.1.4, gateway: 1.1.1.255 }
        - {hostname: pynet-rtr5, ip_addr: 1.1.1.5, gateway: 1.1.1.255 }
