#!/usr/bin/env ansible-playbook
---
#==============================================================================
#title          :exercise4 - week6
#
# Use Ansible to restore your 'primary Ethernet interface' back to the
# following state (or your secondary interface depending on which one you used):
#
# description:           <none>
# switchport mode:       access
# access VLAN:           1
# trunk allowed VLANs:   all
#
# Also use Ansible to remove the three VLANs that you configured.
#
# pynet-sw4
# eapi_username=eapi
# eapi_password=17mendel
# eapi_hostname=184.105.247.75
# eapi_port=443
# primary interface == Ethernet2
#
#author         :Mark Reyes
#date           :Dec 2016
#==============================================================================

- name: Exercise4 - Resetting defaults
  hosts: arista

#--------------------------------------
# Define Tasks

  tasks:
    - name: Remove Description
      eos_interface: name=Ethernet2
            description=''
            username={{ eapi_username }}
            password={{ eapi_password }}
            host={{ eapi_hostname }}
            port={{ eapi_port }}
            transport=https

    - name: Setting that trunk mode
      eos_switchport: name=Ethernet2
            mode=access
            access_vlan=1
            trunk_allowed_vlans=1-4094
            username={{ eapi_username }}
            password={{ eapi_password }}
            host={{ eapi_hostname }}
            port={{ eapi_port }}
            transport=https

    - name: VLAN take down
      eos_vlan: name={{ item.vlan_name }}
            vlanid={{ item.vlan_id }}
            state=absent
            username={{ eapi_username }}
            password={{ eapi_password }}
            host={{ eapi_hostname }}
            port={{ eapi_port }}
            transport=https
      with_items:
        - {vlan_name: RED, vlan_id: 130}
        - {vlan_name: GREEN, vlan_id: 180}
        - {vlan_name: WHITE, vlan_id: 255}

